<a href="https://colab.research.google.com/github/RixzFahad/Met-Data-Science-And-Analyst/blob/main/PandasPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = {
    'id': [1,2,3,4,5,6],
    'employee_name': ['Ser Duncan','Ser Arlan','Ser Steffon','Ser Raymun','Ser Duncan','Ser Arlan'],
    'department': ['Reach','Stormlands','Reach','Vale','Reach','Stormlands'],
    'sales': [1200,800,300,1500,1200,None],
    'profit': [200,150,50,300,200,120],
    'city': ['Delhi','Tokyo','London','Delhi','Delhi','Tokyo'],
    'email': ['a@mail.com','b@mail.com','c@mail.com','a@mail.com','a@mail.com','b@mail.com'],
    'date': ['2025-01-01','2025-01-02','2025-01-03','2025-01-04','2025-01-01','2025-01-02']
}

df = pd.DataFrame(data)
df

,id,employee_name,department,sales,profit,city,email,date
0,1,Ser Duncan,Reach,1200.0,200,Delhi,a@mail.com,2025-01-01
1,2,Ser Arlan,Stormlands,800.0,150,Tokyo,b@mail.com,2025-01-02
2,3,Ser Steffon,Reach,300.0,50,London,c@mail.com,2025-01-03
3,4,Ser Raymun,Vale,1500.0,300,Delhi,a@mail.com,2025-01-04
4,5,Ser Duncan,Reach,1200.0,200,Delhi,a@mail.com,2025-01-01
5,6,Ser Arlan,Stormlands,NaN,120,Tokyo,b@mail.com,2025-01-02

In [ ]:
#I See There Are Some Duplicate Data In This DataSet.
# Remove The Duplicate From Above DataSets

***Checking The Duplicates Values.***

In [6]:
dupes = df[df.duplicated(subset=['employee_name', 'email'], keep=False)]
print(dupes)

   id employee_name  department   sales  profit   city       email        date
0   1    Ser Duncan       Reach  1200.0     200  Delhi  a@mail.com  2025-01-01
1   2     Ser Arlan  Stormlands   800.0     150  Tokyo  b@mail.com  2025-01-02
4   5    Ser Duncan       Reach  1200.0     200  Delhi  a@mail.com  2025-01-01
5   6     Ser Arlan  Stormlands     NaN     120  Tokyo  b@mail.com  2025-01-02

In [7]:
df = df.drop_duplicates()

In [8]:
df

,id,employee_name,department,sales,profit,city,email,date
0,1,Ser Duncan,Reach,1200.0,200,Delhi,a@mail.com,2025-01-01
1,2,Ser Arlan,Stormlands,800.0,150,Tokyo,b@mail.com,2025-01-02
2,3,Ser Steffon,Reach,300.0,50,London,c@mail.com,2025-01-03
3,4,Ser Raymun,Vale,1500.0,300,Delhi,a@mail.com,2025-01-04
4,5,Ser Duncan,Reach,1200.0,200,Delhi,a@mail.com,2025-01-01
5,6,Ser Arlan,Stormlands,NaN,120,Tokyo,b@mail.com,2025-01-02

In [9]:
df['date'] = pd.to_datetime(df['date'])
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month_name()
df['day'] = df['date'].dt.day_name()

AttributeError: 'DataFrame' object has no attribute 'to_datetime'

In [10]:
df['sales'] = df['sales'].fillna(df['sales'].median())
df['department'] = df['department'].fillna('Missing')

In [11]:
df

,id,employee_name,department,sales,profit,city,email,date
0,1,Ser Duncan,Reach,1200.0,200,Delhi,a@mail.com,2025-01-01
1,2,Ser Arlan,Stormlands,800.0,150,Tokyo,b@mail.com,2025-01-02
2,3,Ser Steffon,Reach,300.0,50,London,c@mail.com,2025-01-03
3,4,Ser Raymun,Vale,1500.0,300,Delhi,a@mail.com,2025-01-04
4,5,Ser Duncan,Reach,1200.0,200,Delhi,a@mail.com,2025-01-01
5,6,Ser Arlan,Stormlands,1200.0,120,Tokyo,b@mail.com,2025-01-02

In [12]:
import numpy as np

df['category'] = np.where(df['sales']>1000,'High',
                   np.where(df['sales']>=500,'Medium','Low'))

In [13]:
df

,id,employee_name,department,sales,profit,city,email,date,category
0,1,Ser Duncan,Reach,1200.0,200,Delhi,a@mail.com,2025-01-01,High
1,2,Ser Arlan,Stormlands,800.0,150,Tokyo,b@mail.com,2025-01-02,Medium
2,3,Ser Steffon,Reach,300.0,50,London,c@mail.com,2025-01-03,Low
3,4,Ser Raymun,Vale,1500.0,300,Delhi,a@mail.com,2025-01-04,High
4,5,Ser Duncan,Reach,1200.0,200,Delhi,a@mail.com,2025-01-01,High
5,6,Ser Arlan,Stormlands,1200.0,120,Tokyo,b@mail.com,2025-01-02,High

In [14]:
df['rolling_avg'] = df['sales'].rolling(3,min_periods=1).mean()

In [15]:
df

,id,employee_name,department,sales,profit,city,email,date,category,rolling_avg
0,1,Ser Duncan,Reach,1200.0,200,Delhi,a@mail.com,2025-01-01,High,1200.000000
1,2,Ser Arlan,Stormlands,800.0,150,Tokyo,b@mail.com,2025-01-02,Medium,1000.000000
2,3,Ser Steffon,Reach,300.0,50,London,c@mail.com,2025-01-03,Low,766.666667
3,4,Ser Raymun,Vale,1500.0,300,Delhi,a@mail.com,2025-01-04,High,866.666667
4,5,Ser Duncan,Reach,1200.0,200,Delhi,a@mail.com,2025-01-01,High,1000.000000
5,6,Ser Arlan,Stormlands,1200.0,120,Tokyo,b@mail.com,2025-01-02,High,1300.000000

In [17]:
df.groupby(['department','date']).agg({'sales':['sum','mean','count']})

                        sales
                          sum    mean count
department date
Reach      2025-01-01  2400.0  1200.0     2
           2025-01-03   300.0   300.0     1
Stormlands 2025-01-02  2000.0  1000.0     2
Vale       2025-01-04  1500.0  1500.0     1

In [18]:
df['city'] = df['city'].astype('category')
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             6 non-null      int64
 1   employee_name  6 non-null      object
 2   department     6 non-null      object
 3   sales          6 non-null      float64
 4   profit         6 non-null      int64
 5   city           6 non-null      category
 6   email          6 non-null      object
 7   date           6 non-null      object
 8   category       6 non-null      object
 9   rolling_avg    6 non-null      float64
dtypes: category(1), float64(2), int64(2), object(5)
memory usage: 2.3 KB